version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Twilio
    versions:
    - 5.53.1
    - 5.54.0
    - 5.55.0
    - 5.56.0
    - 5.57.0
    - 5.58.0
  - dependency-name: MailKit
    versions:
    - 2.10.1
    - 2.11.0
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
  - dependency-name: Microsoft.ApplicationInsights.AspNetCore
    versions:
    - 2.16.0
